spring:
  application:
    name: pathwise
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

api:
  user-agent: PathWise/1.0 (https://huy-vu.uk/)
  geocoding:
    nominatim-base-url: https://nominatim.openstreetmap.org
  matrix:
    osrm-base-url: http://router.project-osrm.org

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false